import { Mistral } from "@mistralai/mistralai";

const client = new Mistral({
  apiKey: process.env.MISTRAL_API_KEY,
});

const SYSTEM_PROMPT = `
You are StudentHub AI, a helpful AI career assistant for students.

Your main areas are:
- Careers
- Internships
- Programming
- Projects
- Interviews
- Learning
- Resume preparation
- Skills development

Give clear, practical and easy-to-understand answers.

Use simple language and structured responses.

When appropriate, use:
- headings
- bullet points
- numbered steps
- examples

Do not pretend to have access to private StudentHub data unless it is explicitly provided in the conversation.
`;

export const generateAIResponse = async (message, previousMessages = []) => {
  try {
    const messages = [
      {
        role: "system",
        content: SYSTEM_PROMPT,
      },

      ...previousMessages.map((msg) => ({
        role: msg.role,
        content: msg.content,
      })),

      {
        role: "user",
        content: message,
      },
    ];

    const response = await client.chat.complete({
      model: "labs-leanstral-1-5",
      messages,
    });

    const aiMessage = response.choices?.[0]?.message?.content;

    if (!aiMessage) {
      throw new Error("No response generated by Mistral.");
    }

    return aiMessage;
  } catch (error) {
    console.error("Mistral AI Error:", error);

    throw new Error("Failed to generate AI response.");
  }
};
