import { Mistral } from "@mistralai/mistralai";

const client = new Mistral({
  apiKey: process.env.MISTRAL_API_KEY,
});

const SYSTEM_PROMPT = `
You are StudentHub AI, a helpful AI career assistant for students.

Your main areas are:
- Careers
- Internships
- Programming
- Projects
- Interviews
- Learning
- Resume preparation
- Skills development

Give clear, practical and easy-to-understand answers.

Use simple language and structured responses.

When appropriate, use:
- headings
- bullet points
- numbered steps
- examples

Do not pretend to have access to private StudentHub data unless it is explicitly provided in the conversation.
`;

export const generateAIResponse = async (message, previousMessages = []) => {
  try {
    const messages = [
      {
        role: "system",
        content: SYSTEM_PROMPT,
      },

      ...previousMessages.map((msg) => ({
        role: msg.role,
        content: msg.content,
      })),

      {
        role: "user",
        content: message,
      },
    ];

    const response = await client.chat.complete({
      model: "labs-leanstral-1-5",
      messages,
    });

    const aiMessage = response.choices?.[0]?.message?.content;

    if (!aiMessage) {
      throw new Error("No response generated by Mistral.");
    }

    return aiMessage;
  } catch (error) {
    console.error("Mistral AI Error:", error);

    throw new Error("Failed to generate AI response.");
  }
};

export const analyzeResume = async (resumeText) => {
  try {
    const prompt = `
You are an advanced AI Resume Analyzer for StudentHub.

Analyze the following resume carefully.

Your analysis must evaluate:
- ATS compatibility
- Skills
- Experience
- Education
- Projects
- Resume completeness
- Keywords
- Overall quality
- Suitable career roles

Return ONLY valid JSON.
Do not use markdown.
Do not add explanations outside JSON.

The JSON must follow exactly this structure:

{
  "resumeScore": 0,
  "atsScore": 0,
  "skillsScore": 0,
  "experienceScore": 0,
  "educationScore": 0,
  "projectsScore": 0,
  "completenessScore": 0,

  "skills": [],
  "missingSkills": [],

  "strengths": [],
  "weaknesses": [],
  "suggestions": [],

  "recommendedRoles": [],

  "keywordsFound": [],
  "keywordsMissing": [],
  "keywordMatchPercentage": 0,

  "sectionAnalysis": {
    "summary": {
      "score": 0,
      "feedback": ""
    },
    "education": {
      "score": 0,
      "feedback": ""
    },
    "skills": {
      "score": 0,
      "feedback": ""
    },
    "projects": {
      "score": 0,
      "feedback": ""
    },
    "experience": {
      "score": 0,
      "feedback": ""
    }
  },

  "improvementPriority": [
    {
      "priority": "High",
      "area": "",
      "recommendation": ""
    }
  ]
}

Rules:
- All scores must be between 0 and 100.
- skills should contain skills actually detected in the resume.
- missingSkills should contain useful skills that would improve the candidate's target career direction.
- recommendedRoles should be realistic based only on the resume.
- strengths and weaknesses should be specific.
- suggestions should be practical and actionable.
- keywordsFound should contain important professional/technical keywords detected.
- keywordsMissing should contain useful missing keywords.
- keywordMatchPercentage must be between 0 and 100.
- improvementPriority should prioritize the most important improvements.
- Do not invent work experience, education, projects, certifications, or skills that are not present in the resume.

Resume:

${resumeText}
`;

    const response = await client.chat.complete({
      model: "labs-leanstral-1-5",
      messages: [
        {
          role: "system",
          content:
            "You are a professional ATS resume analyzer. Return only valid JSON.",
        },
        {
          role: "user",
          content: prompt,
        },
      ],
    });

    const aiMessage = response.choices?.[0]?.message?.content;

    if (!aiMessage) {
      throw new Error("No resume analysis generated by Mistral.");
    }

    // Remove accidental markdown code fences
    const cleanedResponse = aiMessage
      .replace(/```json/gi, "")
      .replace(/```/g, "")
      .trim();

    const analysis = JSON.parse(cleanedResponse);

    return analysis;
  } catch (error) {
    console.error("Resume Analysis AI Error:", error);

    throw new Error("Failed to analyze resume.");
  }
};
